services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafe
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cafe
      DB_USER: postgres
      DB_PASS: postgres
      STRIPE_SECRET_KEY: sk_test_xxx
    ports:
      - "4000:4000"
    volumes:
      - ../api:/usr/src/app

  metabase:
    image: metabase/metabase
    restart: always
    depends_on:
      - db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: cafe
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: db
    ports:
      - "3000:3000"

volumes:
  db-data:
